import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import { api } from "~/utils/api";

export default function Home() {
  const hello = api.views.hello.useQuery({text: "from Srijan"})
  const frontends = api.views.getViews.useQuery()

  const user = useUser()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <nav className="flex justify-between border-black border-b-4">
          <div className="text-5xl p-6">
            FRONTENDS
          </div>
          <div className="flex">
          {user.isSignedIn?
            <SignOutButton><button className="bg-red-500 p-5 text-xl w-30 hover:bg-red-600">SIGN OUT</button></SignOutButton> :
            <SignInButton><button className="bg-green-500 p-5 text-xl w-30 hover:bg-green-600">SIGN IN</button></SignInButton>
          }
          </div>
        </nav>
        <div className="text-center">
          {hello.isFetched ? <div>{hello.data?.greeting}</div> : "connecting to tRPC..."} 
          {frontends.data?.map((views) => <div key={views.id}>{views.title}</div>)}
        </div>
      </main>
    </>
  );
}
